group 'com.bivashy.limbo'

repositories {
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation project(':api')
    implementation 'com.github.Revxrsal.Lamp:common:3.0.8'
    implementation 'com.github.Revxrsal.Lamp:velocity:3.0.8'
    compileOnly 'net.kyori:adventure-text-minimessage:4.26.1'
    compileOnly 'org.spongepowered:configurate-yaml:4.2.0'
    compileOnly 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'
}

shadowJar {
    manifest {
        attributes 'Main-Class': 'ua.nanit.limbo.NanoLimbo'
    }
}
